{{- range $name ,$app := .Values.Applications -}}
{{ if .enable }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ default $name .name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "{{ default "0" .syncWave }}"
  labels:
    app.kubernetes.io/part-of: "{{ default "manifest" .partOf }}"    
spec:
  project: {{ default "default" .project }}
  {{- if .sources }} 
  sources:
    {{- toYaml .sources | nindent 2 }}
  {{- end }}     
  destination:
    namespace: {{ default "argocd"  .namespace }}
    server: {{ default "https://kubernetes.default.svc" .server }}
  {{- if .syncPolicy }}   
  syncPolicy:
    {{- toYaml .syncPolicy | nindent 4 }}
  {{- end }}
  {{- if .ignoreDifferences }}
  ignoreDifferences:
    {{- toYaml .ignoreDifferences | nindent 4 }}
  {{- end }} 
    
---
{{- end }}
{{- end }}