{{- range $name, $app := .Values.Projects -}}
{{ if .enable }}
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  {{- if .labels }} 
  labels:
    {{- toYaml .labels | nindent 4 }}
  {{- end }}    
  name: {{ default $name .name }}
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
  annotations:
    argocd.argoproj.io/sync-wave: "{{ default "-1" .syncWave }}" 
  labels:
    app.kubernetes.io/part-of: "{{ default "manifest" .partOf }}"    
spec:
  {{- if .clusterResourceWhitelist }} 
  clusterResourceWhitelist:
    {{- toYaml .clusterResourceWhitelist | nindent 2 }}
  {{- end }}   
  description: {{ .description }}
  {{- if .destinations }} 
  destinations:
    {{- toYaml .destinations | nindent 2 }}
  {{- end }} 
  {{- if .sourceRepos }}   
  sourceRepos:
    {{- toYaml .sourceRepos | nindent 2 }}
  {{- end }} 
---
{{- end }}
{{- end }}  