---
- name: Download rke2
  hosts: 127.0.0.1
  connection: local
  vars:
    helmCharts:
      - gitea-charts/gitea
  tasks:
    - name: Crete Local Temp Dir
      ansible.builtin.file:
        path: "{{ playbook_dir }}/artifacts/temp/{{ item }}"
        state: directory
      loop: 
        - images
        - helmcharts
        - helmcharts/temp
      tags: helm-download  
    - name: Download IMAGES from Bootstrap Helmcharts
      ansible.builtin.shell: helm template {{ item }} | yq -rN '..|.image? | select(.)' | sort | uniq | xargs -I {} bash -c 'docker save {} | gzip > {{ playbook_dir }}/artifacts/temp/images/$(echo {} | sed "s/[\.\/]/-/g").tar.gz'
      loop: "{{ helmCharts }}"
    - name: Download helmcharts for Bootstrap
      ansible.builtin.shell: helm pull {{item}} -d {{ playbook_dir }}/artifacts/temp/helmcharts/temp && ls {{ playbook_dir }}/artifacts/temp/helmcharts/temp/*.tgz | xargs -I {} bash -c 'base64 -i {} > {{ playbook_dir }}/artifacts/temp/helmcharts/$(echo {{item}} | sed "s/[\.\/]/-/g").txt' && rm -rf {{ playbook_dir }}/artifacts/temp/helmcharts/temp/*
      loop: "{{ helmCharts }}"
      tags: helm-download     
    - name: Download rke2-images
      get_url:
        url: "https://github.com/rancher/rke2/releases/download/v1.29.1%2Brke2r1/rke2-images.linux-amd64.tar.zst"
        dest: "{{ playbook_dir }}/artifacts/rke2/rke2-images.linux-amd64.tar.zst"
    - name: Download rke2.linux-amd64
      get_url:
        url: "https://github.com/rancher/rke2/releases/download/v1.29.1%2Brke2r1/rke2.linux-amd64.tar.gz"
        dest: "{{ playbook_dir }}/artifacts/rke2/rke2.linux-amd64.tar.gz"
    - name: Download sha256sum-amd64
      get_url:
        url: "https://github.com/rancher/rke2/releases/download/v1.29.1%2Brke2r1/sha256sum-amd64.txt"
        dest: "{{ playbook_dir }}/artifacts/rke2/sha256sum-amd64.txt"
    - name: Download install.sh
      get_url:
        url: "https://get.rke2.io"
        dest: "{{ playbook_dir }}/artifacts/rke2/install.sh"            

- name: Install RKE2 in master nodes
  hosts: master_nodes
  become: true
  tasks:
    - name: Crete Artifact Directory
      ansible.builtin.file:
        path: /root/rke2-artifacts
        state: directory
    - name: Crete images directory
      ansible.builtin.file:
        path: /var/lib/rancher/rke2/agent/images/
        state: directory
    - name: Crete Config Directory
      ansible.builtin.file:
        path: /etc/rancher/rke2/
        state: directory           
    - name: Copy rke2-images.linux-amd64.tar.zst
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/artifacts/rke2/rke2-images.linux-amd64.tar.zst"
        dest: /root/rke2-artifacts/rke2-images.linux-amd64.tar.zst
    - name: Copy rke2.linux-amd64.tar.gz
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/artifacts/rke2/rke2.linux-amd64.tar.gz"
        dest: /root/rke2-artifacts/rke2.linux-amd64.tar.gz
    - name: Copy sha256sum-amd64.txt
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/artifacts/rke2/sha256sum-amd64.txt"
        dest: /root/rke2-artifacts/sha256sum-amd64.txt
    - name: Copy config file
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/artifacts/rke2/master_nodes/{{ inventory_hostname }}/config.yaml"
        dest: /etc/rancher/rke2/config.yaml    
    - name: Copy install.sh
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/artifacts/rke2/install.sh"
        dest: /root/rke2-artifacts/install.sh
        mode: 0755
    - name: Install rke2
      environment:
        INSTALL_RKE2_ARTIFACT_PATH: /root/rke2-artifacts
        INSTALL_RKE2_TYPE: "server"
        INSTALL_RKE2_METHOD: "tar"
      ansible.builtin.command: /root/rke2-artifacts/install.sh
    - name: Start RKE2 service
      throttle: 1
      ansible.builtin.systemd_service:
        state: restarted
        enabled: yes
        name: rke2-server.service
- name: Install RKE2 in agent nodes
  hosts: agent_nodes
  become: true
  tasks:
    - name: Crete Artifact Directory
      ansible.builtin.file:
        path: /root/rke2-artifacts
        state: directory
    - name: Crete images directory
      ansible.builtin.file:
        path: /var/lib/rancher/rke2/agent/images/
        state: directory
    - name: Crete Config Directory
      ansible.builtin.file:
        path: /etc/rancher/rke2/
        state: directory          
    - name: Copy rke2-images.linux-amd64.tar.zst
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/artifacts/rke2/rke2-images.linux-amd64.tar.zst"
        dest: /root/rke2-artifacts/rke2-images.linux-amd64.tar.zst
    - name: Copy rke2.linux-amd64.tar.gz
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/artifacts/rke2/rke2.linux-amd64.tar.gz"
        dest: /root/rke2-artifacts/rke2.linux-amd64.tar.gz
    - name: Copy sha256sum-amd64.txt
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/artifacts/rke2/sha256sum-amd64.txt"
        dest: /root/rke2-artifacts/sha256sum-amd64.txt
    - name: Copy config file
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/artifacts/rke2/agent_nodes/{{ inventory_hostname }}/config.yaml"
        dest: /etc/rancher/rke2/config.yaml       
    - name: Copy install.sh
      ansible.builtin.copy:
        src: "{{ playbook_dir }}/artifacts/rke2/install.sh"
        dest: /root/rke2-artifacts/install.sh
        mode: 0755
    - name: Install rke2
      environment:
        INSTALL_RKE2_ARTIFACT_PATH: /root/rke2-artifacts
        INSTALL_RKE2_TYPE: "agent"
        INSTALL_RKE2_METHOD: "tar"
      ansible.builtin.command: /root/rke2-artifacts/install.sh
    - name: Start RKE2 service
      ansible.builtin.systemd_service:
        state: restarted
        enabled: yes
        name: rke2-agent.service                 